### ISSUE TITLE
Confidence intervals and IRFs

### ISSUE THREAD

**Issue by fipelle** [fipelle/MessyTimeSeries.jl#12]
> Nice! 
> Is it possible to compute conf intervals for the forecasts? 
> 
> Also, I'm not sure if this is w/i the scope of your package, but it's often convenient to derive [IRFs w/ confidence bands](http://lenkiefer.com/2020/02/25/housing-response-to-a-consumer-confidence-shock/). 
> Luca has some [nice Julia options here](https://github.com/lucabrugnolini/VectorAutoregressions.jl).

_Originally posted by @azev77 in https://github.com/fipelle/TSAnalysis.jl/issues/9#issuecomment-604054920_

---

**Confidence intervals**

Although there is not a high-level interface to compute the confidence intervals yet, you could use the variance in the output of the Kalman filter or the subsampling methods. The latter is easier to implement. For instance, you could follow the steps below:
1. Compute the coefficients for a series of data partitions - for instance, generated with the artificial delete-*d* jackknife or the stationary bootstrap;
2. Compute a range of forecasts with the real data (and not the random partitions) using, in turn, each matrix of coefficients generated in the previous point;
3. Compute the empirical confidence intervals.

---

**Impulse response functions**

I know Luca, I am sure that the VectorAutoregression package is a good way to go for computing impulse response functions. I am not sure I will extend support to the IRFs anytime soon. I think I will give priority to other forecasting models (e.g., dynamic factor models) and basic analytics. However, I recon that it would be interesting to look at the IRFs of semi-structural models.

**Comment by azev77** [comment]
Sounds good. 
Unfortunately VectorAutoregression.jl doesn't currently work & isn't being upgraded...

**Comment by greimel** [comment]
xref https://github.com/lucabrugnolini/VectorAutoregressions.jl/pull/8


VectorAutoregressions now passes tests under Julia 1.6

**Comment by fipelle** [comment]
Thank you for this! I will get back to these features once a series of compatibility issues are resolved.

**Comment by fipelle** [comment]
It would be good to have some cross interface between VectorAutoregressions.jl and MessyTimeSeriesOptim.jl to compute the IRFs of the models estimated with the latter (either just for VARs or VMA and DFMs as well).

**Comment by azev77** [comment]
It says the issue was closed. 
Does that mean IRFs are now included?

**Comment by fipelle** [comment]
@azev77 they are not online yet, but I have a private repo I am testing with the IRFs. They will be included in MessyTimeSeriesOptim.jl.
