### ISSUE TITLE
Fitted Trend Line and Residuals

### ISSUE THREAD

**Issue by Sinansi** [fipelle/MessyTimeSeries.jl#13]
Hello,

I see you have provided examples on predicting 12 intervals in the future. But I seek past values. Can you please give more examples on how to generate fitted line and residuals on a time series using arima and varima? 

Thank you!

**Comment by fipelle** [comment]
Hi, 

The code does not currently have a simple interface for producing in-sample predictions for the levels, using VARIMA models (it would require some small changes in the forecast function). However, it is quite easy to get the in-sample forecast / residuals of the underlying VARMA models. Would that help?

**Comment by Sinansi** [comment]
Thanks for your reply!

I am not an expert with time series decomposition. Can you give a brief example on how to extract the trend (forecast) and residuals for in-sample (past data) using VARIMA?

**Comment by fipelle** [comment]
Hi,

Trend-cycle decompositions based on VARIMA models are not implemented yet. I would suggest you to take a look at the multivariate Beveridge and Nelson decomposition. 

Alternatively, you could use any state-space model described in Harvey (1990). They are actually much easier to implement with the current status of the package. I am happy to give you more details on that if you can let me know which model would work best. An example is already reported in the **Estimation of state-space models** section in the readme.



--

**Bibliography**

Harvey, Andrew C. Forecasting, structural time series models and the Kalman filter. Cambridge university press, 1990.

**Comment by Sinansi** [comment]
@fipelle oh I was commenting at the same moment you were replying :)
I will have a look at it, and get back to you.

**Comment by fipelle** [comment]
Happy to help! I am currently updating the library offline, I will start again adding features relatively soon. The Beveridge and Nelson decomposition in on my list, but there is quite some stuff to add before that I am afraid. 

PS: As mentioned, you can get the in-sample prediction and residuals for a VARMA (not a VARIMA). If that is what you actually want to do I can work out an example.

**Comment by fipelle** [comment]
I am moving it to a private todo list and closing the issue. I should get back to it soon. Please take a look at MessyTimeSeriesOptim.jl in the meantime, as I may implement it there.
