### ISSUE TITLE
Tag new release with correct Distribution compat 

### ISSUE THREAD

**Issue by gbaraldi** [fipelle/MessyTimeSeries.jl#27]
As was talked in this Discourse [thread](https://discourse.julialang.org/t/understanding-dependencies-of-a-package/71347). An open compat bound means that General added a very low bound and that breaks packages in the same environment. So tagging a new release with a fixed Project file would fix that.

**Comment by fipelle** [comment]
Thanks, I have replied to the thread on Discourse. 

TL;DR
I am going to release a major update in the following two weeks which should solve most issues.

**Comment by fipelle** [comment]
This should have been solved now. Let me know if the problem persists with the v0.2 release.
